workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - echo "Starting Android build"
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "amandeep184404@gmail.com"
